version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    volumes:
      - ./:/app
    command: ["air", "-c", ".air.toml"]
    environment:
      - AIR_ADDRESS=0.0.0.0:8585